extends Node

# {{name}} — entrypoint.
# Generated by `esp create`. Lifecycle methods called by the ESP mod loader:
#   esp_preload(api, meta) -> bool   # before dependencies are guaranteed
#   esp_init(api, meta)    -> bool   # main setup; return false to fail the mod
#   esp_ready(api, meta)             # all mods initialized; safe to talk to peers
#
# `api` is /root/ESP — see scripts/core/esp_api.gd in the framework for the full
# namespaced surface. `meta` is this mod's parsed mod.json plus runtime fields.

const MOD_ID := "{{id}}"

var api: Node
var meta: Dictionary

func esp_init(p_api: Node, p_meta: Dictionary) -> bool:
    api = p_api
    meta = p_meta
    api.log_info("[%s] init" % MOD_ID)
    return true

func esp_ready(_api: Node, _meta: Dictionary) -> void:
    api.log_info("[%s] ready" % MOD_ID)
